/* Automatically generated by "build-radpaths-h" */
#define LOGDIR		"/opt/sas4/freeradius/var/log/radius"
#define LIBDIR		"/opt/sas4/freeradius/lib"
#define RADDBDIR	"/opt/sas4/freeradius/etc/raddb"
#define RUNDIR		"/opt/sas4/freeradius/var/run"
#define SBINDIR		"/opt/sas4/freeradius/sbin"
#define RADIR		"/opt/sas4/freeradius/var/log/radius/radacct"
#define DICTDIR		"/opt/sas4/freeradius/share/freeradius"
