name: sasman_radius_app
description: "SASMAN RADIUS mobile application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  file_picker: ^8.0.1
  url_launcher: ^6.3.0
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
