
package radius

import (
	"fmt"
	"log"
	"os"
)

func SyncNASToFile() {
	rows, err := DB.Query("SELECT nasname, secret, shortname FROM nas")
	if err != nil {
		log.Printf("[radius] Error loading NAS for sync: %v", err)
		return
	}
	defer rows.Close()

	content := "# Auto-generated by SASMAN\n"
	for rows.Next() {
		var ip, secret, name string
		rows.Scan(&ip, &secret, &name)
		content += fmt.Sprintf("client nas_%s {\n\tipaddr = %s\n\tsecret = %s\n\tshortname = %s\n}\n\n", name, ip, secret, name)
	}

	err = os.WriteFile("/app/data/radius_db/clients.conf", []byte(content), 0644)
	if err != nil {
		log.Printf("[radius] Error writing NAS clients file: %v", err)
	}
}
